In [113]:
import numpy as np

# Use the following code for questions 1 - 8

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [114]:
# 1. How many negative numbers are there?

len(a[a < 0])

4

In [115]:
# 2. How many positive numbers are there?

len(a[a > 0])

5

In [116]:
# 3. How many even positive numbers are there?

len(a[(a > 0) & (a % 2 == 0)])

# print(len(a[a > 0]) & len(a[a % 2 == 0]))

3

In [117]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
 
len(a[(a + 3) > 0])

10

In [118]:
# 5. If you squared each number, what would the new mean and standard deviation be?

print(np.mean(a ** 2))
print(np.std(a ** 2))

74.0
144.0243035046516


In [119]:
# 6. A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0.
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

print(a - np.mean(a))

print(np.mean(a - np.mean(a)))

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
0.0


In [120]:
# 7. Calculate the z-score for each data point. Recall that the z-score is given by:

print((a - np.mean(a)) / np.std(a))

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [121]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

In [122]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = 0

for i in a:
    sum_of_a += i

sum_of_a

55

In [123]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = a[0]

for i in a:
    if i < min_of_a:
        min_of_a = i
        
print(min_of_a)


1


In [124]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = a[0]
for num in a:
    if num > max_of_a:
        max_of_a = num
print(max_of_a)

10


In [125]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


In [126]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = 1

for num in a:
    product_of_a *= num
    
print(product_of_a)

3628800


In [127]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [128]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = []

for num in a:
    if num % 2 == 1:
        odds_in_a.append(num)

print(odds_in_a)

[1, 3, 5, 7, 9]


In [129]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = []

for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)
        
print(evens_in_a)

[2, 4, 6, 8, 10]


In [143]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Convert b to an array.
np.array(b)

array([[3, 4, 5],
       [6, 7, 8]])

In [131]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
print(sum_of_b)

np.array(b)
sum_of_b = np.sum(b)
print(sum_of_b)

33
33


In [132]:

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
print(min_of_b)

print(np.min(b))

3
3


In [133]:

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)

print(np.max(b))

8
8


In [134]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)

print(np.mean(b))

5.5
5.5


In [135]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(product_of_b)

print(np.prod(b))

20160
20160


In [136]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)

print(np.square(b))

[9, 16, 25, 36, 49, 64]
[[ 9 16 25]
 [36 49 64]]


In [137]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

# print(b[b % 2 == 1])

[3, 5, 7]


In [138]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

# print(b[b % 2 == 0])

[4, 6, 8]


In [139]:
# Exercise 9 - print out the shape of the array b.

np.shape(b)

(2, 3)

In [140]:
# Exercise 10 - transpose the array b.

np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [146]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b.reshape(1,6)

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

c = np.array(c)

In [ ]:
# Exercise 1 - Find the min, max, sum, and product of c.

print(np.min(c))
print(np.max(c))
print(np.sum(c))
print(np.prod(c))

1
9
45
362880


In [ ]:
# Exercise 2 - Determine the standard deviation of c.

np.std(c)

2.581988897471611

In [ ]:
# Exercise 3 - Determine the variance of c.

np.var(c)

6.666666666666667

In [ ]:
# Exercise 4 - Print out the shape of the array c

np.shape(c)

(3, 3)

In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

np.sum(c * np.transpose(c))

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

np.prod(c * np.transpose(c))

131681894400

In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

d[d < 0]

array([-90, -30, -45, -45])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [ ]:
# Exercise 8 - Print out the shape of d.

np.shape(d)

(3, 6)

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

np.transpose(d).shape

(6, 3)

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])